# -------- BUILD STAGE --------
FROM golang:1.24-alpine AS builder

WORKDIR /app

ENV GOTOOLCHAIN=local

# Needed for downloading modules
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o auth ./cmd

# -------- RUNTIME STAGE --------
FROM alpine:3.19

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/auth ./auth
COPY --from=builder /app/migrations ./migrations

EXPOSE 9001

ENV PORT=9001

ENTRYPOINT ["./auth"]
